services:
  - type: web
    name: medibot
    env: python
    buildCommand: pip install torch --index-url https://download.pytorch.org/whl/cpu && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENV
        value: us-east-1
      - key: PINECONE_INDEX
        value: medical-chatbot
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: "false"